apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-sitef
  labels:
    app: project-sitef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-sitef
  template:
    metadata:
      labels:
        app: project-sitef
    spec:
      containers:
      - name: project-sitef
        image: akhandanand/project-sitef:{{ .Values.image.tag }}
        ports:
        - containerPort: 80

