apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-sitef
  labels:
    app: project-sitef
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: project-sitef
  template:
    metadata:
      labels:
        app: project-sitef
    spec:
      containers:
      - name: project-sitef
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80

